language: node_js

node_js:
  - "node"
  - "16"
  - "14"
  - "12"
  - "11"

sudo: false

git:
  submodules: false

before_script:
  - npm install

script:
  - npm run test
# after_success:
#   - npm run report-coveralls
#   - npm run report-codecov
